spring:
  application:
    name: employed-service
  data:
    mongodb:
      uri: mongodb://camiloval1999:Ccva1007@ac-qfqxsfs-shard-00-00.uwbtkk8.mongodb.net:27017,ac-qfqxsfs-shard-00-01.uwbtkk8.mongodb.net:27017,ac-qfqxsfs-shard-00-02.uwbtkk8.mongodb.net:27017/barber?ssl=true&replicaSet=atlas-d048n8-shard-0&authSource=admin&retryWrites=true&w=majority

server:
  port: 0

user-service:
  service:
    url: lb://USER-SERVICE